In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv(r"C:\indian_ecommerce_sales\customers.csv")
products = pd.read_csv(r"C:\indian_ecommerce_sales\products.csv")
sales = pd.read_csv(r"C:\indian_ecommerce_sales\sales.csv")

In [3]:
customers_copy = customers.copy()
products_copy = products.copy()
sales_copy = sales.copy()

In [4]:
customers.columns = customers.columns.str.strip()
products.columns = products.columns.str.strip()
sales.columns = sales.columns.str.strip()

In [5]:
customers.head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Customer_Segment,Signup_Date
0,CUST000001,Arjun Menon,Male,37.0,Guntur,Andhra Pradesh,Regular,2022-10-09
1,CUST000002,Aarav Iyer,Female,23.0,Rajkot,Gujarat,Regular,2019-06-25
2,CUST000003,Priya Yadav,Male,46.0,Gwalior,Madhya Pradesh,Loyal,2024-04-11
3,CUST000004,Neha Mishra,Female,60.0,Jodhpur,Rajasthan,Regular,2025-04-23
4,CUST000005,Ananya Mishra,Female,43.0,Mumbai,Maharashtra,Loyal,2021-05-28

In [6]:
products.head()

,Product_ID,Product_Name,Category,Sub_Category,Brand,Base_Price_INR,Cost_Price_INR,Stock_Level,Supplier_Rating
0,PROD00001,Ziva Appliances 0001,Home & Kitchen,Appliances,Ziva,1441.05,963.42,844,5.0
1,PROD00002,Mitra Skincare 0002,Beauty,Skincare,StyleHub,1225.63,664.10,873,4.0
2,PROD00003,Nova Personal Care 0003,beauty,Personal Care,Apex,399.22,209.03,464,4.6
3,PROD00004,DailyNeeds Organic 0004,Grocery,Organic,UrbanKart,1065.85,726.78,319,4.6
4,PROD00005,HomeNest Home Decor 0005,Home & Kitchen,Home Decor,Apex,800.98,619.36,359,2.5

In [7]:
sales.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Unit_Price_INR,Discount,Sales_Amount_INR,Cost_Amount_INR,Profit_INR,Payment_Method,Order_Status,Sales_Channel
0,ORD00000001,2022-08-15,CUST009626,PROD00057,2.0,4368.38,0.00,8736.76,6061.54,2675.22,UPI,Delivered,Website
1,ORD00000002,2024-06-16,CUST046209,PROD00776,1.0,319.78,0.40,319.78,355.48,-35.70,Credit Card,Delivered,Website
2,ORD00000003,2022-01-19,CUST031593,PROD00753,1.0,128.53,0.05,128.53,78.43,50.10,Debit Card,Shipped,Mobile App
3,ORD00000004,2024-02-27,CUST044467,PROD00150,1.0,107.79,0.15,107.79,96.70,11.09,Credit Card,Delivered,Website
4,ORD00000005,2024-11-29,CUST049123,PROD00930,1.0,622.00,0.05,622.00,530.14,91.86,Net Banking,Delivered,Mobile App

In [8]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 50150 entries, 0 to 50149
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       50150 non-null  str
 1   Customer_Name     50150 non-null  str
 2   Gender            50000 non-null  str
 3   Age               49748 non-null  float64
 4   City              49853 non-null  str
 5   State             49947 non-null  str
 6   Customer_Segment  50150 non-null  str
 7   Signup_Date       50150 non-null  str
dtypes: float64(1), str(7)
memory usage: 3.1 MB

In [9]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product_ID       1000 non-null   str
 1   Product_Name     1000 non-null   str
 2   Category         1000 non-null   str
 3   Sub_Category     1000 non-null   str
 4   Brand            1000 non-null   str
 5   Base_Price_INR   1000 non-null   float64
 6   Cost_Price_INR   960 non-null    float64
 7   Stock_Level      1000 non-null   int64
 8   Supplier_Rating  1000 non-null   float64
dtypes: float64(3), int64(1), str(5)
memory usage: 70.4 KB

In [10]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 500500 entries, 0 to 500499
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order_ID          500500 non-null  str
 1   Order_Date        500500 non-null  str
 2   Customer_ID       499501 non-null  str
 3   Product_ID        500500 non-null  str
 4   Quantity          498999 non-null  float64
 5   Unit_Price_INR    500500 non-null  float64
 6   Discount          497500 non-null  float64
 7   Sales_Amount_INR  500500 non-null  float64
 8   Cost_Amount_INR   500500 non-null  float64
 9   Profit_INR        500500 non-null  float64
 10  Payment_Method    494496 non-null  str
 11  Order_Status      499500 non-null  str
 12  Sales_Channel     500500 non-null  str
dtypes: float64(6), str(7)
memory usage: 49.6 MB

In [11]:
customers.describe(include="all")

,Customer_ID,Customer_Name,Gender,Age,City,State,Customer_Segment,Signup_Date
count,50150,50150,50000,49748.000000,49853,49947,50150,50150
unique,50000,400,3,NaN,131,30,4,2372
top,CUST000023,Rahul Singh,Male,NaN,Aurangabad,Maharashtra,Regular,2025-01-20
freq,2,161,24557,NaN,1131,5363,22351,40
mean,NaN,NaN,NaN,43.880236,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,15.289498,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,18.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,31.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,44.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,57.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,70.000000,NaN,NaN,NaN,NaN

In [12]:
products.describe(include="all")

,Product_ID,Product_Name,Category,Sub_Category,Brand,Base_Price_INR,Cost_Price_INR,Stock_Level,Supplier_Rating
count,1000,1000,1000,1000,1000,1000.000000,960.000000,1000.000000,1000.000000
unique,1000,1000,16,65,10,NaN,NaN,NaN,NaN
top,PROD00001,Ziva Appliances 0001,Fashion,Kids Wear,HomeNest,NaN,NaN,NaN,NaN
freq,1,1,153,40,116,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,7234.488130,4913.496792,509.282000,3.748400
std,NaN,NaN,NaN,NaN,NaN,11011.527618,7181.453702,289.763793,0.722689
min,NaN,NaN,NaN,NaN,NaN,-22965.550000,61.700000,0.000000,2.500000
25%,NaN,NaN,NaN,NaN,NaN,446.677500,329.242500,255.000000,3.100000
50%,NaN,NaN,NaN,NaN,NaN,2112.760000,1435.395000,514.000000,3.800000
75%,NaN,NaN,NaN,NaN,NaN,9586.715000,6568.505000,757.000000,4.400000
max,NaN,NaN,NaN,NaN,NaN,44872.780000,34024.850000,999.000000,5.000000

In [13]:
sales.describe(include="all")

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Unit_Price_INR,Discount,Sales_Amount_INR,Cost_Amount_INR,Profit_INR,Payment_Method,Order_Status,Sales_Channel
count,500500,500500,499501,500500,498999.000000,500500.000000,497500.000000,5.005000e+05,500500.000000,500500.000000,494496,499500,500500
unique,500000,1641,50000,1001,NaN,NaN,NaN,NaN,NaN,NaN,12,11,3
top,ORD00000400,2021-03-30,CUST999999,PROD00563,NaN,NaN,NaN,NaN,NaN,NaN,UPI,Delivered,Mobile App
freq,2,364,150,567,NaN,NaN,NaN,NaN,NaN,NaN,176888,368008,250271
mean,NaN,NaN,NaN,NaN,2.175918,6626.346482,0.117589,1.437530e+04,10189.194236,4132.195393,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,1.812674,9595.126920,0.086632,2.933157e+04,20558.225363,10260.365557,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,-4.000000,72.170000,0.000000,7.217000e+01,0.000000,-53441.100000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,1.000000,456.820000,0.050000,7.894375e+02,476.250000,162.180000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,2.000000,2007.580000,0.100000,3.546680e+03,2267.670000,763.200000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,3.000000,8909.870000,0.150000,1.519435e+04,10414.620000,3741.555000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,99.000000,44872.780000,0.900000,3.066847e+06,340248.500000,431364.800000,NaN,NaN,NaN

In [14]:
print("Customers")
print(customers.isnull().sum())

print("\nProducts")
print(products.isnull().sum())

print("\nSales")
print(sales.isnull().sum())

Customers
Customer_ID           0
Customer_Name         0
Gender              150
Age                 402
City                297
State               203
Customer_Segment      0
Signup_Date           0
dtype: int64

Products
Product_ID          0
Product_Name        0
Category            0
Sub_Category        0
Brand               0
Base_Price_INR      0
Cost_Price_INR     40
Stock_Level         0
Supplier_Rating     0
dtype: int64

Sales
Order_ID               0
Order_Date             0
Customer_ID          999
Product_ID             0
Quantity            1501
Unit_Price_INR         0
Discount            3000
Sales_Amount_INR       0
Cost_Amount_INR        0
Profit_INR             0
Payment_Method      6004
Order_Status        1000
Sales_Channel          0
dtype: int64

In [15]:
#Checking Duplicates

In [16]:
print("Customer_ID Duplicates")
print(customers["Customer_ID"].duplicated().sum())

print("\nOrder_ID Duplicates")
print(sales["Order_ID"].duplicated().sum())

Customer_ID Duplicates
150

Order_ID Duplicates
500

In [17]:
customers[customers["Customer_ID"].duplicated(keep=False)].sort_values("Customer_ID")

,Customer_ID,Customer_Name,Gender,Age,City,State,Customer_Segment,Signup_Date
22,CUST000023,Vivaan Shetty,Male,32.0,Patna,Bihar,Regular,2024-08-12
50068,CUST000023,Vivaan Shetty,Male,32.0,Patna,Bihar,Regular,2024-08-12
213,CUST000214,Aarav Menon,Female,64.0,Tirupati,Andhra Pradesh,New,2020-05-15
50094,CUST000214,Aarav Menon,Female,64.0,Tirupati,Andhra Pradesh,New,2020-05-15
246,CUST000247,Aisha Menon,Male,46.0,Agra,Uttar Pradesh,Loyal,2024-07-19
...,...,...,...,...,...,...,...,...
50145,CUST049039,Meera Kumar,Female,18.0,Kozhikode,Kerala,Loyal,2019-02-16
49387,CUST049388,Karan Choudhary,Male,38.0,Kolkata,West Bengal,VIP,2025-01-01
50080,CUST049388,Karan Choudhary,Male,38.0,Kolkata,West Bengal,VIP,2025-01-01
50057,CUST049585,Riya Mehta,Male,19.0,Gwalior,Madhya Pradesh,Regular,2020-01-20
49584,CUST049585,Riya Mehta,Male,19.0,Gwalior,Madhya Pradesh,Regular,2020-01-20

In [18]:
sales[sales["Order_ID"].duplicated(keep=False)].sort_values("Order_ID")

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Unit_Price_INR,Discount,Sales_Amount_INR,Cost_Amount_INR,Profit_INR,Payment_Method,Order_Status,Sales_Channel
399,ORD00000400,2022-08-01,CUST016006,PROD00884,2.0,743.47,0.25,1486.94,1617.52,-130.58,Debit Card,Delivered,Mobile App
500206,ORD00000400,2022-08-01,CUST016006,PROD00884,2.0,743.47,0.25,1486.94,1617.52,-130.58,Debit Card,Delivered,Mobile App
894,ORD00000895,2022-03-17,CUST029236,PROD00679,1.0,258.89,0.05,258.89,137.91,120.98,Net Banking,Delivered,Mobile App
500101,ORD00000895,2022-03-17,CUST029236,PROD00679,1.0,258.89,0.05,258.89,137.91,120.98,Net Banking,Delivered,Mobile App
5979,ORD00005980,2024-01-17,CUST037648,PROD00190,2.0,13135.28,0.10,26270.56,15302.10,10968.46,Credit Card,Delivered,Mobile App
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495765,ORD00495766,2025-06-07,CUST018540,PROD00543,1.0,24792.00,0.10,24792.00,18426.47,6365.53,Debit Card,Delivered,Website
500488,ORD00496615,2025-04-12,CUST031131,PROD00809,1.0,843.66,0.30,843.66,694.13,149.53,Debit Card,Delivered,Website
496614,ORD00496615,2025-04-12,CUST031131,PROD00809,1.0,843.66,0.30,843.66,694.13,149.53,Debit Card,Delivered,Website
500327,ORD00499861,2022-09-05,CUST020898,PROD00194,2.0,40385.50,0.10,80771.00,54294.30,26476.70,Cash on Delivery,Delivered,Website
499860,ORD00499861,2022-09-05,CUST020898,PROD00194,2.0,40385.50,0.10,80771.00,54294.30,26476.70,Cash on Delivery,Delivered,Website

In [19]:
customers = customers.drop_duplicates()
sales = sales.drop_duplicates()

In [20]:
print("Customers")
print(customers.duplicated().sum())

print("\nSales")
print(sales.duplicated().sum())

Customers
0

Sales
0

In [21]:
#Filling Missing Values

In [22]:
products[products["Cost_Price_INR"].isnull()]

,Product_ID,Product_Name,Category,Sub_Category,Brand,Base_Price_INR,Cost_Price_INR,Stock_Level,Supplier_Rating
9,PROD00010,TechPro Makeup 0010,Beauty,Makeup,UrbanKart,395.04,NaN,996,4.9
14,PROD00015,Mitra Cycling 0015,Sports,Cycling,Ziva,5201.02,NaN,29,4.3
22,PROD00023,HomeNest Haircare 0023,Beauty,Haircare,Ziva,594.19,NaN,481,4.0
91,PROD00092,StyleHub Appliances 0092,Home & Kitchen,Appliances,StyleHub,1031.25,NaN,940,3.5
135,PROD00136,DailyNeeds Makeup 0136,Beauty,Makeup,Mitra,3879.96,NaN,757,3.0
177,PROD00178,Apex Men Clothing 0178,Fashion,Men Clothing,TechPro,6756.31,NaN,372,3.9
200,PROD00201,Mitra Competitive Exams 0201,Books,Competitive Exams,Nova,43098.22,NaN,83,4.4
225,PROD00226,Apex Footwear 0226,Fashion,Footwear,Nova,707.18,NaN,941,4.9
249,PROD00250,Nova Laptop 0250,Electronics,Laptop,HomeNest,1748.55,NaN,298,3.7
350,PROD00351,TechPro Cricket 0351,Sports,Cricket,Nova,4895.18,NaN,749,4.2
370,PROD00371,Ziva Smartwatch 0371,Electronics,Smartwatch,UrbanKart,1214.05,NaN,835,3.3
397,PROD00398,UrbanKart Laptop 0398,Electronics,Laptop,DailyNeeds,10176.98,NaN,611,4.5
442,PROD00443,PrimeChoice Organic 0443,Grocery,Organic,StyleHub,17945.68,NaN,977,4.2
454,PROD00455,PrimeChoice Smartwatch 0455,Electronics,Smartwatch,Mitra,2043.83,NaN,816,2.5
504,PROD00505,PrimeChoice Women Clothing 0505,Fashion,Women Clothing,HomeNest,15655.94,NaN,671,4.5
537,PROD00538,Ziva Accessories 0538,Electronics,Accessories,PrimeChoice,140.97,NaN,793,3.6
559,PROD00560,Apex Appliances 0560,Home & Kitchen,Appliances,UrbanKart,39603.61,NaN,91,4.2
565,PROD00566,DailyNeeds Men Clothing 0566,Fashion,MEN CLOTHING,Nova,6753.22,NaN,886,4.2
574,PROD00575,Mitra Phone Cases 0575,Accessories,Phone Cases,TechPro,6024.46,NaN,120,3.1
596,PROD00597,UrbanKart Packaged Food 0597,Grocery,Packaged Food,UrbanKart,1699.99,NaN,41,4.8
606,PROD00607,Ziva Footwear 0607,Fashion,Footwear,Mitra,6446.34,NaN,272,4.6
610,PROD00611,Ziva Television 0611,Electronics,Television,HomeNest,4886.63,NaN,723,4.6
629,PROD00630,Mitra Headphones 0630,Electronics,Headphones,TechPro,393.83,NaN,69,4.9
647,PROD00648,Nova Business 0648,Books,Business,Ziva,9070.55,NaN,653,4.4
700,PROD00701,StyleHub Staples 0701,Grocery,Staples,Nova,1899.10,NaN,975,4.2
724,PROD00725,Ziva Snacks 0725,Grocery,Snacks,Apex,759.22,NaN,302,3.9
736,PROD00737,PrimeChoice Wallets 0737,Accessories,Wallets,Apex,314.40,NaN,431,4.8
746,PROD00747,StyleHub Mobile 0747,Electronics,Mobile,Ziva,287.05,NaN,804,3.9
785,PROD00786,UrbanKart Mobile 0786,Electronics,Mobile,DailyNeeds,8627.43,NaN,625,3.1
786,PROD00787,Ziva Storage 0787,Home & Kitchen,Storage,HomeNest,1417.69,NaN,712,4.7
826,PROD00827,Apex Beverages 0827,Grocery,Beverages,UrbanKart,11131.39,NaN,801,4.2
838,PROD00839,HomeNest Watches 0839,Accessories,Watches,DailyNeeds,2450.84,NaN,982,4.3
857,PROD00858,TechPro Appliances 0858,Home & Kitchen,Appliances,Nova,43136.48,NaN,15,2.7
889,PROD00890,Apex Bags 0890,Fashion,Bags,Mitra,134.05,NaN,644,3.6
893,PROD00894,Mitra Kids Wear 0894,Fashion,Kids Wear,DailyNeeds,625.63,NaN,620,3.7
903,PROD00904,PrimeChoice Appliances 0904,home & kitchen,APPLIANCES,Mitra,299.39,NaN,23,4.4
916,PROD00917,HomeNest Skincare 0917,Beauty,Skincare,UrbanKart,12263.84,NaN,255,3.6
932,PROD00933,Ziva Smartwatch 0933,electronics,Smartwatch,Nova,446.31,NaN,684,3.3
958,PROD00959,StyleHub Laptop 0959,Electronics,Laptop,TechPro,7494.11,NaN,459,3.4
998,PROD00999,Mitra Phone Cases 0999,Accessories,Phone Cases,Apex,1523.48,NaN,232,4.2

In [23]:
Category_Ratio = products.groupby("Category")["Cost_Price_INR"].transform("median")

products["Cost_Price_INR"] = products["Cost_Price_INR"].fillna(products["Base_Price_INR"]*Category_Ratio)

In [24]:
#Filtering Negative Values

In [25]:
products[["Cost_Price_INR","Base_Price_INR"]].describe()

       Cost_Price_INR  Base_Price_INR
count    9.990000e+02     1000.000000
mean     5.375496e+05     7234.488130
std      5.443927e+06    11011.527618
min      6.170000e+01   -22965.550000
25%      3.502150e+02      446.677500
50%      1.717210e+03     2112.760000
75%      8.056455e+03     9586.715000
max      1.048659e+08    44872.780000

In [26]:
#Storing Negative Values
Negative_Products = products.loc[products["Base_Price_INR"] < 0, "Product_ID"] 

sales[sales["Product_ID"].isin(Negative_Products)].shape

(15148, 13)

In [27]:
#Filtering
products = products[products["Base_Price_INR"] >=0]

In [28]:
Missing_Quantity = sales[sales["Quantity"].isnull()].copy()

In [29]:
Missing_Quantity["Calculated_Qty"] = (Missing_Quantity["Sales_Amount_INR"]/Missing_Quantity["Unit_Price_INR"])

In [30]:
#Validating Sales

In [31]:
Negative_Mask = sales["Quantity"] < 0

In [32]:
sales.loc[Negative_Mask,"Quantity"] = (sales.loc[Negative_Mask,"Sales_Amount_INR"]/sales.loc[Negative_Mask,"Unit_Price_INR"]).round()

In [33]:
sales["Quantity"] = sales["Quantity"].fillna(sales["Sales_Amount_INR"]/sales["Unit_Price_INR"]).round()

In [34]:
sales[sales["Quantity"].isnull()].shape

(0, 13)

In [46]:
#Standardizing Text Values
sales[["Sales_Channel","Payment_Method","Order_Status"]] = sales[["Sales_Channel","Payment_Method","Order_Status"]].apply(lambda x : x.str.title())

In [49]:
sales["Discount"].value_counts(dropna=False).sort_index()

Discount
0.00     74514
0.05     99739
0.10    114189
0.15     89104
0.20     59628
0.25     34991
0.30     19706
0.40      5030
0.55         1
0.56         1
0.57         1
0.58         2
0.59         3
0.60         7
0.61         1
0.62         4
0.63         1
0.64         2
0.65         3
0.66         1
0.68         1
0.69         5
0.70         4
0.71         2
0.72         3
0.73         5
0.74         3
0.75         2
0.77         5
0.78         5
0.79         3
0.80         1
0.81         4
0.82         3
0.83         3
0.84         1
0.85         3
0.86         8
0.87         4
0.88         3
0.89         3
0.90         2
NaN       2999
Name: count, dtype: int64

In [53]:
sales["Order_Status"] = sales["Order_Status"].fillna("Unknown")

In [55]:
sales["Order_Status"] = sales["Order_Status"].str.replace("Nan","Unknown")

In [67]:
#Data Quality Check

In [60]:
sales[sales["Customer_ID"].isna()]

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Unit_Price_INR,Discount,Sales_Amount_INR,Cost_Amount_INR,Profit_INR,Payment_Method,Order_Status,Sales_Channel
355,ORD00000356,2023-01-02,NaN,PROD00898,1.0,324.55,0.30,324.55,247.84,76.71,Upi,Shipped,Website
499,ORD00000500,2023-07-28,NaN,PROD00728,1.0,984.09,0.15,984.09,618.15,365.94,Debit Card,Returned,Website
1013,ORD00001014,2021-04-14,NaN,PROD00720,4.0,28975.30,0.20,115901.20,84785.76,31115.44,Upi,Shipped,Mobile App
1211,ORD00001212,2024-12-16,NaN,PROD00771,1.0,136.03,0.15,136.03,101.91,34.12,Cash On Delivery,Delivered,Website
1836,ORD00001837,2022-12-08,NaN,PROD00399,4.0,1277.71,0.05,5110.84,3319.56,1791.28,Cash On Delivery,Delivered,Mobile App
...,...,...,...,...,...,...,...,...,...,...,...,...,...
498672,ORD00498673,2021-01-05,NaN,PROD00264,1.0,9163.04,0.10,9163.04,5063.85,4099.19,Cash On Delivery,Delivered,Mobile App
498833,ORD00498834,2021-09-19,NaN,PROD00980,1.0,4031.84,0.15,4031.84,2420.20,1611.64,Credit Card,Delivered,Mobile App
498850,ORD00498851,2024-08-23,NaN,PROD00350,5.0,2244.82,0.15,11224.10,6674.30,4549.80,Upi,Pending,Mobile App
499395,ORD00499396,2024-06-20,NaN,PROD00107,1.0,217.97,0.15,217.97,126.86,91.11,Credit Card,Shipped,Website
499646,ORD00499647,2024-07-13,NaN,PROD00491,4.0,37673.97,0.10,150695.88,81801.52,68894.36,Upi,Delivered,Mobile App

In [61]:
missing_customer_ids = sales[sales["Customer_ID"].isna()]

In [63]:
missing_customer_ids[
    ["Order_ID", "Customer_ID", "Product_ID", "Order_Date",
     "Sales_Amount_INR", "Order_Status"]
].head(10)

,Order_ID,Customer_ID,Product_ID,Order_Date,Sales_Amount_INR,Order_Status
355,ORD00000356,NaN,PROD00898,2023-01-02,324.55,Shipped
499,ORD00000500,NaN,PROD00728,2023-07-28,984.09,Returned
1013,ORD00001014,NaN,PROD00720,2021-04-14,115901.20,Shipped
1211,ORD00001212,NaN,PROD00771,2024-12-16,136.03,Delivered
1836,ORD00001837,NaN,PROD00399,2022-12-08,5110.84,Delivered
2555,ORD00002556,NaN,PROD00074,2022-01-22,531.63,Delivered
4192,ORD00004193,NaN,PROD00743,2024-12-29,362.60,Returned
5756,ORD00005757,NaN,PROD00852,2021-08-24,2058.54,Delivered
5822,ORD00005823,NaN,PROD00318,2021-10-31,3596.25,Shipped
7336,ORD00007337,NaN,PROD00075,2024-11-19,186.95,Pending

In [64]:
sales.loc[sales["Customer_ID"].notna()&sales["Customer_ID"].isin(customers["Customer_ID"]),"Customer_ID"].nunique()

49999

In [66]:
# Check sales Product_ID values not found in products
sales.loc[
    ~sales["Product_ID"].isin(products["Product_ID"]),
    "Product_ID"
].nunique()

31

This section summarizes the data-quality issues identified during cleaning and validation.
Missing values and unmatched customer/product IDs are retained without further modification.

In [68]:
customers.to_csv("YC_cleaned_customers",index=False)
products.to_csv("YC_cleaned_products",index=False)
sales.to_csv("YC_cleaned_sales",index=False)